[toolchain]
channel = "nightly"
components = [
    "clippy-preview",
    "llvm-tools-preview",
    "rustfmt",
    "rust-src",
    "rust-std",
    "cargo",
	"clippy",
	"rust-analyzer",
	"rust-src",
	"rust-std",
	"rustc-dev",
	"rustc",
	"rustfmt"
]
targets = [ "wasm32-unknown-unknown" ]
profile = "minimal"
